CC = gcc
CFLAGS = -Wall -pedantic -Wextra -Wcast-align -Winit-self -Wno-unused-parameter -std=c11 -O2
LDFLAGS = -lusb-1.0

all: main.c
	${CC} ${CFLAGS} main.c -o getUsbString ${LDFLAGS}

clean:
	rm getUsbString
